services:
  mjakazi-connect:
    image: ghcr.io/m6-o4/mjakazi-connect:latest
    container_name: payload-template-project
    restart: unless-stopped
    networks:
      - m6o4-prd-network
    env_file:
      - stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mjakazi-connect.rule=Host(`mjakaziconnect.co.ke`) ||
        Host(`www.mjakaziconnect.co.ke`)"
      - "traefik.http.routers.mjakazi-connect.entrypoints=websecure"
      - "traefik.http.routers.mjakazi-connect.tls.certresolver=letsencrypt"
      - "traefik.http.services.mjakazi-connect.loadbalancer.server.port=3000"

networks:
  m6o4-prd-network:
    external: true
    name: m6o4-prd-network
